# Generated by Django 4.1.3 on 2022-12-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markattendence', models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('leave request', 'leave request')], default=1, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ViewMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
